### ISSUE TITLE
[bug]: When running the UI in docker, the url localhost:port/en does not work

### ISSUE THREAD

**Issue by apo-j** [featbit/featbit#11]
## Describe the bug
When running the UI in docker, the url localhost:port/en does not work

## To Reproduce
I ran the UI with
```
docker build -t featbit/ui .
docker run -d -p 8080:80 --name featbit-ui featbit/ui
```
In the navigator, if I put localhost:8080 or localhost:8080/en/, everything works like a charme,
but when I tried with localhost:8080/en, it's not working and the browser is redirected to localhost/en
It's obvious the port is missing

## Expected behavior
It should work with localhost:8080/en

## Browser
N/A

## Additional context
N/A

**Comment by cosmos-explorer** [comment]
Thank you, we will look at this issue as soon as possible
