### ISSUE TITLE
[bug]: All modals have two close buttons

### ISSUE THREAD

**Issue by apo-j** [featbit/featbit#16]
## Describe

All modals have two close buttons

## To Reproduce
![image](https://user-images.githubusercontent.com/88151306/189245006-887e5110-b3ba-46ca-868a-e24fbd373ec9.png)

## Expected behavior
Only one close button is expected

## Browser
N/A

## Additional context
N/A

**Comment by cosmos-explorer** [comment]
@cosmos-explorer wil check this
