### ISSUE TITLE
[BUG] The container name/port may conflict when user run docker-compose up -d

### ISSUE THREAD

**Issue by luluchou** [featbit/featbit#163]
**Describe the bug**  
When user try our system with `docker-compose up -d`, container name/port may conflict

**To Reproduce**
Steps to reproduce the behavior
```shell
# create a redis container named 'redis' and bind port 6379 to it
docker run -d -p 6379:6379 --name redis redis

# change directory to featbit
cd featbit

# up featbit
docker-compose up -d
```
we can see this error
`Error response from daemon: Conflict. The container name "/redis" is already in use by container "74d8d135781f10e373849e6c24bde7a6cbb37d55443eae87b31bae79791217e8". You have to remove (or rename) that container to be able to reuse that name.`

**Expected behavior**
featbit system should be launched

**Comment by deleteLater** [comment]
To solve the port conflict problem, you can see our docs here:

https://featbit.gitbook.io/docs/installation#how-to-solve-docker-container-port-conflict-problem
