### ISSUE TITLE
.NET SDK

### ISSUE THREAD

**Issue by cosmic-flood** [featbit/featbit#168]
### Discussed in https://github.com/orgs/featbit/discussions/113

<div type='discussions-op-text'>

<sup>Originally posted by **MOGUIJOE** November 22, 2022</sup>
You guys are good at Dot NET. Why don’t you provide a .NET SDK ?</div>

**Comment by deleteLater** [comment]
- [ ] create NuGet account
- [ ]

**Comment by deleteLater** [comment]
Preliminary design work has been completed. Implementation will be moved to another pr.
