### ISSUE TITLE
Performance reporting

### ISSUE THREAD

**Issue by cosmic-flood** [featbit/featbit#169]
### Discussed in https://github.com/orgs/featbit/discussions/140

<div type='discussions-op-text'>

<sup>Originally posted by **cosmic-flood** December  5, 2022</sup>
![image](https://user-images.githubusercontent.com/68597908/205601593-495f8f3c-2228-41c9-8a0f-ee44364e6e26.png)
</div>

- [x] tools
- [x] setup environment
- [x] seed data
- [x] run script strategy
- [x] report + text description

**Comment by deleteLater** [comment]
The design work has been completed. Implementation will be moved to another pr.
