### ISSUE TITLE
[Bug]: lacking Go SDK sample  in docs

### ISSUE THREAD

**Issue by wenfengwang** [featbit/featbit#170]
### What happened?

On this page, Go SDK has listed.
![image](https://user-images.githubusercontent.com/9766821/208288683-25d115ae-eeef-45cb-80cb-6581127ff492.png)

When I clicked the link, the below page was shown.
![image](https://user-images.githubusercontent.com/9766821/208288708-f124113f-fdf6-49d2-b613-f1480d5864b5.png)

Plus, Sidebar also lacks Go SDK demo.
![image](https://user-images.githubusercontent.com/9766821/208288770-cebbe0b3-1359-4821-bdf9-f77ff4dc4240.png)

### To Reproduce

see https://featbit.gitbook.io/docs/getting-started/4.-connect-an-sdk/server-side-sdks#go

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by cosmic-flood** [comment]
Issue fixed
