### ISSUE TITLE
[Bug]: Scroller bug on policy setting page

### ISSUE THREAD

**Issue by cosmic-flood** [featbit/featbit#197]
### What happened?

I can't scroll down to add a new policy action setting on policy's permission tab

### To Reproduce

![image](https://user-images.githubusercontent.com/68597908/211047951-3ca2cd69-9484-4303-b7bc-7b14d8ba4c64.png)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by cosmos-explorer** [comment]
Not a bug. You wrongly placed your navigator under the task bar and part of the navigator is actually out of the screen
