### ISSUE TITLE
[Good First Issue]: Difficult to manage list items in feature flag and segment targeting rules

### ISSUE THREAD

**Issue by cosmic-flood** [featbit/featbit#225]
### What happened?

As shown below, It's hard to see and manage items in the list.

For example, I tried to add 10 business customers' name in the list, and some of their names have the same beginning. The current design is very inconvenient.

![image](https://user-images.githubusercontent.com/68597908/215102467-43c6f398-fa27-4229-9bec-46ab4e0668da.png)

![image](https://user-images.githubusercontent.com/68597908/215101435-4b43413e-6bad-4d3f-a377-1f1f07bf4cba.png)

Here is a design made by others that might help you to improve.

![image](https://user-images.githubusercontent.com/68597908/215103198-a4846f11-0934-4eba-99a7-5958d4ec1a6c.png)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by cosmic-flood** [comment]
Added to project's draft

**Comment by sagar110599** [comment]
hi @cosmic-flood i could give the above issue a try.

**Comment by cosmic-flood** [comment]
> hi @cosmic-flood i could give the above issue a try. If possible can assign this to me.

Hi @sagar110599  Do you have any idea of how will you make the enhancement? (about UI & UX)
