### ISSUE TITLE
[Good First Issues]: Hide edit button on permission setting page for system managed permissions

### ISSUE THREAD

**Issue by cosmos-explorer** [featbit/featbit#234]
# Description
FeatBit has built a identity access and management (IAM) system inspired by AWS IAM. The access to all resources within FeatBit is configured via IAM.

Policy is a set of statement that defines permissions (Allow or Deny) of some actions to resources. There are 2 types of policy:
- System managed policy : the FeatBit built in policies
- Customer managed policy : customer created policies

System managed policies are readonly, users are not allowed to make any changes to them. The only allowed action is to make a copy then it becomes a customer managed policy. To learn more, [read the documentation](https://featbit.gitbook.io/docs/iam/policies)

As a system managed policy is readonly, user should not be able to change its name and description. The protection is already done in the backend, but in the UI, the edit buttons are still available. The present task is to hide those buttons on system managed policies.

# Scope
Tech stack: Angular 14.0
Service： UI
Component： IAM -> Policies
Files to modify: modules\front-end\src\app\features\safe\iam\policies\details\setting\

# Screenshot
![image](https://user-images.githubusercontent.com/88151306/220933894-6a774f32-e9b1-4e83-9e9a-e7ba18a69e94.png)

# How to implement

1. Fork the FeatBit repository.
2. Create a branch issues-{issues number}
3. Implement the task based on Description and Scope mentioned above.
4. Submit your PR

# Contribution points

Each issue counts specific points based on its difficulty. Contributors earn the corresponding points if they solve that issue. Contribution points are used to describe the contributions contributors have made. They can also be used to get rewards when there are community events.

This issue counts 4 points.

# How to claim to solve the issue

If you want to implement this function, please leave a comment in this issue like:

| I'd like to implement this function, please assign this issue to me.

FeatBit community will assign the issue to you on time.

**Comment by san-ki** [comment]
I would like to work on this one.
