### ISSUE TITLE
Contribution: Make comment optional when updating segment & feature flag targeting

### ISSUE THREAD

**Issue by cosmos-explorer** [featbit/featbit#235]
# Description
The Audit log is a running tally of changes made to feature flags and segments in a given environment. You can access the audit log from the side menu. To learn more, [read the documentation](https://featbit.gitbook.io/docs/feature-flags/audit-log)

Whenever a change is made to a feature flag or a segment, the user is required to review the changes, edit a comment then save it. 

Currently, the comment is a mandatory field. This is very unconvenient as sometimes the user may have no comments on it. The present task is to **make the comment field optional**. 

# Scope
Tech stack: Angular 14.0
Service： UI
Component： core components -> change-view
Files to modify: modules\front-end\src\app\core\components\change-review\

# Screenshot
![image](https://user-images.githubusercontent.com/88151306/220938033-cbb5fc91-b830-4ff2-bed4-171ece630fe6.png)

**Comment by Michaelg22** [comment]
Id like to contribute to this issue please assign it to me
