### ISSUE TITLE
[Good First Issues]: Add description to feature flag Front-End

### ISSUE THREAD

**Issue by cosmos-explorer** [featbit/featbit#236]
# Description
We use feature flags to manage features in any software. After creation a feature flag, it happens that we may forget the purpose and scope of the it, then a block of text to describe the flag could helpful. The present task is to **add a description field to feature flag**. 

# Scope
Tech stack: 
- Angular 14.0

Service： UI
Component： feature flags -> details -> setting
Files to modify: modules\front-end\src\app\features\safe\feature-flags\details\setting\

# Screenshot
![image](https://user-images.githubusercontent.com/88151306/220944348-39bb2341-e2f1-40d6-8679-8c429cf9154d.png)

**Take the following screen as an example**
![image](https://user-images.githubusercontent.com/88151306/220950426-78702925-8116-4cec-9da5-cce0fdf6e83e.png)

# Setup dev environment

Please read the [doc](../../Development.md) to set up your development environment.

# Deadline

We usually give 2 weeks for a feature request, which means you have 2 weeks to implement the feature starting from the day it is assigned to you. If you have any difficulties, please contact us in [Slack](https://join.slack.com/t/featbit/shared_invite/zt-1ew5e2vbb-x6Apan1xZOaYMnFzqZkGNQ).

# How to implement

1. Fork the FeatBit repository.
2. Create a branch issues-{issues number}
3. Implement the task based on Description and Scope mentioned above.
4. Submit your PR

# Contribution points

Each contribution counts a certain number of points, depending on its difficulty. Contributors earn the appropriate points when the work is merged. Contribution points are used to describe the contributions that contributors have made. They can also be used to receive rewards for community events. You can view the current community submissions on a public [google sheet](https://docs.google.com/spreadsheets/d/1ukyXgi_jRPeXj7EAST0IrnPfLOQ6xDBkcyAJY9N-Yb4/edit#gid=0).

Points: 4

# How to claim to solve the issue

If you want to implement this function, please leave a comment in this issue like:

| I'd like to implement this function, please assign this issue to me.

FeatBit community will assign the issue to you on time.

**Comment by kabir-webDev** [comment]
Hello brother, I have 2 years of experience in front-end development. 
But I never contributed in Open Source project. 
Your project looks interesting to me. 
I would like to contribute.
Can you please assign this issue to me?
I would do the front-end part only.

**Comment by cosmic-flood** [comment]
> Hello brother, I have 2 years of experience in front-end development. But I never contributed in Open Source project. Your project looks interesting to me. I would like to contribute. Can you please assign this issue to me? I would do the front-end part only.

Hi @kabir-webDev 

Thank you for your self-referral. When @cosmos-explorer is available, he will do the assignment and guide you on how to contribute.

**Comment by cosmos-explorer** [comment]
Hello @kabir-webDev, thanks for your interesting, I have modifed the issue scope to front-end only.
