### ISSUE TITLE
[Good First Issues]: Add description to feature flag creation modal

### ISSUE THREAD

**Issue by cosmos-explorer** [featbit/featbit#237]
# Description
We use feature flags to manage features in any software. After creation a feature flag, it happens that we may forget the purpose and scope of the it, then a block of text to describe the flag could helpful. The present task is to **add a description field to feature flag creation modal**. 

# Scope
Tech stack: 
- dotnet 

Service： API
Component： feature flags
Files to modify: modules\back-end\src\Api\Controllers\FeatureFlagController.cs : CreateAsync

# Screenshot
![image](https://user-images.githubusercontent.com/88151306/220949517-bb4966fc-946e-4bec-8063-5ce5b75f5b4f.png)

**Take the following screen as an example**
![image](https://user-images.githubusercontent.com/88151306/220950926-08d9358d-f329-4f30-9033-dd11abc8f3d0.png)

# Contribution points

Each contribution counts a certain number of points, depending on its difficulty. Contributors earn the appropriate points when the work is merged. Contribution points are used to describe the contributions that contributors have made. They can also be used to receive rewards for community events. You can view the current community submissions on a public [google sheet](https://docs.google.com/spreadsheets/d/1ukyXgi_jRPeXj7EAST0IrnPfLOQ6xDBkcyAJY9N-Yb4/edit#gid=0).

Points: 4

# How to claim to solve the issue

If you want to implement this function, please leave a comment in this issue like:

| I'd like to implement this function, please assign this issue to me.

FeatBit community will assign the issue to you on time.

**Comment by sagar110599** [comment]
Hi @cosmos-explorer would love to contribute to this issue as well.

**Comment by cosmic-flood** [comment]
Hi, @sagar110599 

Thanks for contacting us. When @cosmos-explorer is available, he will do the assignment and guide you on contributing.

While you wait for the assignment, you can join our Slack community. https://join.slack.com/t/featbit/shared_invite/zt-1ew5e2vbb-x6Apan1xZOaYMnFzqZkGNQ

**Comment by cosmos-explorer** [comment]
Hello @sagar110599 , Thank you for your interest to FeatBit. I just assigned both issues to you. If you have any question, please join our Slack channel

**Comment by deleteLater** [comment]
closed by #258

**Comment by deleteLater** [comment]
resolved in #258
