### ISSUE TITLE
[Good First Issues]: Add description to feature flag API

### ISSUE THREAD

**Issue by cosmos-explorer** [featbit/featbit#243]
# Description
We use feature flags to manage features in any software. After creation a feature flag, it happens that we may forget the purpose and scope of the it, then a block of text to describe the flag could helpful. The present task is to add a description field to feature flag.

# Scope
Tech stack: 
- dotnet 

Service： API
Component： feature flags
Files to modify: modules\back-end\src\Api\Controllers\FeatureFlagController.cs : UpdateSettingAsync

# How to implement

1. Fork the FeatBit repository.
2. Create a branch issues-{issues number}
3. Implement the task based on Description and Scope mentioned above.
4. Submit your PR

# Contribution points

Each contribution counts a certain number of points, depending on its difficulty. Contributors earn the appropriate points when the work is merged. Contribution points are used to describe the contributions that contributors have made. They can also be used to receive rewards for community events. You can view the current community submissions on a public [google sheet](https://docs.google.com/spreadsheets/d/1ukyXgi_jRPeXj7EAST0IrnPfLOQ6xDBkcyAJY9N-Yb4/edit#gid=0).

Points: 4

# How to claim to solve the issue

If you want to implement this function, please leave a comment in this issue like:

| I'd like to implement this function, please assign this issue to me.

FeatBit community will assign the issue to you on time.

**Comment by DaveFz** [comment]
Hey I'd like to take the issue. Can you assign me?

**Comment by cosmic-flood** [comment]
> Hey I'd like to take the issue. Can you assign me?

Hi, @DaveFz . Thanks for contacting us. When @cosmos-explorer is available, he will do the assignment and guide you on how to contribute.

While you wait for the assignment, you can join our Slack community. https://join.slack.com/t/featbit/shared_invite/zt-1ew5e2vbb-x6Apan1xZOaYMnFzqZkGNQ

**Comment by cosmos-explorer** [comment]
Thank you @DaveFz, just assigned the issue to you. If you have any questions, please join our slack channel. We usually have two weeks for a typical **good firsts issue**, please let us know if you have any difficulty.

**Comment by deleteLater** [comment]
closed by #258
