### ISSUE TITLE
[Good First Issues]: Add description to feature flag creation modal

### ISSUE THREAD

**Issue by cosmos-explorer** [featbit/featbit#257]
# Description
We use feature flags to manage features in any software. After creation a feature flag, it happens that we may forget the purpose and scope of the it, then a block of text to describe the flag could helpful. The present task is to **add a description field to feature flag creation modal**. 

# Scope
Tech stack: 
- Angular 14.0

Service： UI
Component： feature flags -> index
Files to modify: modules\front-end\src\app\features\safe\feature-flags\index\

# Screenshot
![image](https://user-images.githubusercontent.com/88151306/220949517-bb4966fc-946e-4bec-8063-5ce5b75f5b4f.png)

**Take the following screen as an example**
![image](https://user-images.githubusercontent.com/88151306/220950926-08d9358d-f329-4f30-9033-dd11abc8f3d0.png)

# Contribution points

Each contribution counts a certain number of points, depending on its difficulty. Contributors earn the appropriate points when the work is merged. Contribution points are used to describe the contributions that contributors have made. They can also be used to receive rewards for community events. You can view the current community submissions on a public [google sheet](https://docs.google.com/spreadsheets/d/1ukyXgi_jRPeXj7EAST0IrnPfLOQ6xDBkcyAJY9N-Yb4/edit#gid=0).

Points: 4

# How to claim to solve the issue

If you want to implement this function, please leave a comment in this issue like:

| I'd like to implement this function, please assign this issue to me.

FeatBit community will assign the issue to you on time.

**Comment by sagar110599** [comment]
Hi @cosmos-explorer I would like to contribute to this issue.
