### ISSUE TITLE
[Good First Issues]: AuditLog supports changes to feature flag description

### ISSUE THREAD

**Issue by cosmos-explorer** [featbit/featbit#262]
# Description
Currently the **AuditLog** feature logs all changes to feature flags and segments. As we have added the new field **description** to feature flag previously in the PRs https://github.com/featbit/featbit/pull/259 and https://github.com/featbit/featbit/pull/258 , we need to support this field in **AuditLog**.

# Scope
Tech stack:

Angular 14.0

Component： feature flags -> details -> setting
Files to modify: modules\front-end\src\app\features\safe\feature-flags\details\setting\

# Screenshot
Whe the PR is done, you should be able to see this:
![image](https://user-images.githubusercontent.com/88151306/223295470-7c685c2a-2037-4a99-8442-9d5ac20f2f4b.png)

# Setup dev environment

Please read the [doc](../../Development.md) to set up your development environment.

# Deadline

We usually give 2 weeks for a feature request, which means you have 2 weeks to implement the feature starting from the day it is assigned to you. If you have any difficulties, please contact us in [Slack](https://join.slack.com/t/featbit/shared_invite/zt-1ew5e2vbb-x6Apan1xZOaYMnFzqZkGNQ).

# How to implement

1. Open the file [feature-flag.differ.ts](https://github.com/featbit/featbit/blob/main/modules/front-end/src/app/shared/diff/feature-flag.differ.ts)
2. After line 12 add `{ label: $localize `:@@differ.description:description`, path: ['description'] },`

Make sure to run  `npm run i18n` at the end of the work and commit the following files:
- [messages.xlf](https://github.com/featbit/featbit/blob/main/modules/front-end/src/locale/messages.xlf)
- [messages.zh.xlf](https://github.com/featbit/featbit/blob/main/modules/front-end/src/locale/messages.zh.xlf)

# Contribution points

Each contribution counts a certain number of points, depending on its difficulty. Contributors earn the appropriate
points when the work is merged. Contribution points are used to describe the contributions that contributors have made.
They can also be used to receive rewards for community events. You can view the current community submissions on a
public [google sheet](https://docs.google.com/spreadsheets/d/1ukyXgi_jRPeXj7EAST0IrnPfLOQ6xDBkcyAJY9N-Yb4/edit#gid=1117970540).

Points: 4

# How to claim to solve the issue

If you want to implement this function, please leave a comment in this issue like:

> I'd like to implement this function, please assign this issue to me.

FeatBit community will assign the issue to you on time.

**Comment by kabir-webDev** [comment]
I'd like to implement this function, please assign this issue to me.

**Comment by kabir-webDev** [comment]
I think this issue should be closed now as the PR has been merged.
