### ISSUE TITLE
[BUG] The organization name in the top-right corner is incorrect after updating the name in the Organization Settings

### ISSUE THREAD

**Issue by cosmic-flood** [featbit/featbit#331]
## Describe the bug
The organization name in the top-right corner is incorrect after updating the name in the Organization Settings.

## To Reproduce
1. Go to page 'https://tryitonline.featbit.co/en/organizations'
2. Change Name and Click 'Update'
3. Refresh the page
4. Org name in the top-right corner is not the name I just changed in step 2.

If you are the one who updated the org name, then you won't see any problems. But if someone else in the same organization has changed the name on another computer or if you modify the name in one navigator and check in another navigator (you have already visited FeatBit UI with the second navigator), you will be able to reproduce the bug.

## Expected behavior
The org name in the top-right corner should be updated to match what I configured on the organization page.

## Screenshots
![gRGDtphaCr](https://user-images.githubusercontent.com/68597908/233682529-a0a55feb-a0fa-4aeb-937e-b8e0921108c5.jpg)

## Setup dev environment

Please read the [doc](../blob/main/Development.md) to set up your development environment.

## Contribution points

Each contribution counts a certain number of points, depending on its difficulty. Contributors earn the appropriate
points when the work is merged. Contribution points are used to describe the contributions that contributors have made.
They can also be used to receive rewards for community events. You can view the current community submissions on a
public [google sheet](https://docs.google.com/spreadsheets/d/1ukyXgi_jRPeXj7EAST0IrnPfLOQ6xDBkcyAJY9N-Yb4/edit#gid=1117970540).

Points: 6

## How to claim to solve the issue

If you want to implement this function, please leave a comment in this issue like:

> I'd like to implement this function, please assign this issue to me.

FeatBit community will assign the issue to you on time.

**Comment by reynadess** [comment]
@cosmic-flood I tried reproducing the issue from the above steps. I think it is working as expected.

**Comment by cosmos-explorer** [comment]
> @cosmic-flood I tried reproducing the issue from the above steps. I think it is working as expected.

@reynadess if you are the one who updated the org name, then you won't see any problems. But if someone else in the same organization has changed the name on another computer or if you modify the name in one navigator and check in another navigator (you have already visited FeatBit UI with the second navigator), you will be able to reproduce the bug.

**Comment by cosmic-flood** [comment]
Hi @reynadess  Would you like to contribute to this issue?

**Comment by reynadess** [comment]
@cosmic-flood Will comment if taking up this issue.

**Comment by cosmic-flood** [comment]
> if you are the one who updated the org name, then you won't see any problems. But if someone else in the same organization has changed the name on another computer or if you modify the name in one navigator and check in another navigator (you have already visited FeatBit UI with the second navigator), you will be able to reproduce the bug.

Hi @talhatahir 

If you are the one who updated the org name, then you won't see any problems. But if someone else in the same organization has changed the name on another computer or if you modify the name in one navigator and check in another navigator (you have already visited FeatBit UI with the second navigator), you will be able to reproduce the bug.

**Comment by cosmic-flood** [comment]
> Alright, now i understand it. Was able to reproduce it. Let me look at a fix for this.

Thank you @talhatahir 

Instead of communicating here, you can also [join our Slack channel ](https://join.slack.com/t/featbit/shared_invite/zt-1ew5e2vbb-x6Apan1xZOaYMnFzqZkGNQ)to chat, as you prefer.

**Comment by mucoban** [comment]
hi @cosmic-flood, @deleteLater, I created a pr for this issue
