### ISSUE TITLE
[Good First Issue]: Unify Feature Flag On/Off Confirm Messages

### ISSUE THREAD

**Issue by deleteLater** [featbit/featbit#333]
# Description

We want to unify the turn feature flag on/off confirm messages for better user experience. Below is the messages we proposed.

## Turn Flag On Confirm Message
- `i18n-nz-popconfirm="@@ff.are-you-sure-to-turn-ff-on"`
- `nz-popconfirm="Are you sure to turn it on? The flag will return the matching targeting users' or rules' serving variation."`
- Chinese translation: 确定要打开开关么？打开后开关将按照既定规则匹配用户返回值。

## Turn flag Off Confirm Message
- `i18n-nz-popconfirm="@@ff.are-you-sure-to-turn-ff-off"`
- `nz-popconfirm="Are you sure to turn it off? The flag will return the variation that you specified for its off state."`
- Chinese translation: 确定要关闭开关么？关闭后开关将返回处于关闭状态时的设定值。

# Scope

- Service: UI
- Components: feature flag index and settings components
- The files need to be changed: 
   - modules/front-end/src/app/features/safe/feature-flags/index/index.component.html. Line 56-57
   - modules/front-end/src/app/features/safe/feature-flags/details/setting/setting.component.html. Line 97-98 104-105

# Screenshot

## feature flag index component
![image](https://user-images.githubusercontent.com/34052208/234234648-a5f91444-cb47-4f16-b589-3751c3f63a20.png)

## feature flag settings component
![image](https://user-images.githubusercontent.com/34052208/234240221-5b189f0e-2cb6-4bb1-8052-7595ddea6d27.png)

# Setup dev environment

Please read the [doc](../blob/main/Development.md) to set up your development environment.

# Deadline

We usually give 2 weeks for a feature request, which means you have 2 weeks to implement the feature starting from the day it is assigned to you. If you have any difficulties, please contact us in [Slack](https://join.slack.com/t/featbit/shared_invite/zt-1ew5e2vbb-x6Apan1xZOaYMnFzqZkGNQ).

# How to implement

1. Fork the FeatBit repository.
2. Create a branch issues-{issues number}
3. Implement the task based on Description and Scope mentioned above.
4. Submit your PR

Make sure you complete the following tasks before submit your PR:
- merge featbit main branch into your working branch
- run `npm run i18n`
- commit **messages.xlf & messages.zh.xlf** file changes (if any)

# Contribution points

Each contribution counts a certain number of points, depending on its difficulty. Contributors earn the appropriate
points when the work is merged. Contribution points are used to describe the contributions that contributors have made.
They can also be used to receive rewards for community events. You can view the current community submissions on a
public [google sheet](https://docs.google.com/spreadsheets/d/1ukyXgi_jRPeXj7EAST0IrnPfLOQ6xDBkcyAJY9N-Yb4/edit#gid=1117970540).

Points: 4

# How to claim to solve the issue

If you want to implement this function, please leave a comment in this issue like:

> I'd like to implement this function, please assign this issue to me.

**Comment by Shubh8899** [comment]
I'd like to implement this function, please assign this issue to me.

**Comment by deleteLater** [comment]
Thanks @Shubh8899, I've assigned this issue to you 🤝
