### ISSUE TITLE
[Good First Issue]: Make the Access Token drawer style consistent

### ISSUE THREAD

**Issue by deleteLater** [featbit/featbit#335]
# Description
The current style of the Access Token drawer does not meet our design standards. To fix this, two tasks need to be done:
- Update the save button style to match the rest of the application.
- Change the drawer width from 700 to 500.

# Scope
- Service: UI
- Component: Access Token drawer component
- Location: modules/front-end/src/app/core/components/access-token-drawer

To make the save button style consistent with others, we should place the save button in the `nzDrawerContent` element instead of the `footer` element. Just like how policy drawer does [here](https://github.com/featbit/featbit/blob/main/modules/front-end/src/app/core/components/policy-drawer/policy-drawer.component.html#L32).

# Screenshot

## Current
![image](https://user-images.githubusercontent.com/34052208/234626282-06b61de4-6305-4da1-9e9a-3c6f2fc0a402.png)

## Expected
![image](https://user-images.githubusercontent.com/34052208/234626625-8e69990c-78e8-4b44-8440-0337a50994c7.png)

# Setup dev environment

Please read the [doc](../blob/main/Development.md) to set up your development environment.

# Deadline

We usually give 2 weeks for a feature request, which means you have 2 weeks to implement the feature starting from the
day it is assigned to you. If you have any difficulties, please contact us in [Slack](https://join.slack.com/t/featbit/shared_invite/zt-1ew5e2vbb-x6Apan1xZOaYMnFzqZkGNQ).

# How to implement

1. Fork the FeatBit repository.
2. Create a branch issues-{issues number}
3. Implement the task based on Description and Scope mentioned above.
4. Submit your PR

Make sure you complete the following tasks before submit your PR

- merge featbit main branch into your working branch
- run `npm run i18n`
- commit **messages.xlf & messages.zh.xlf** file changes

# Contribution points

Each contribution counts a certain number of points, depending on its difficulty. Contributors earn the appropriate
points when the work is merged. Contribution points are used to describe the contributions that contributors have made.
They can also be used to receive rewards for community events. You can view the current community submissions on a
public [google sheet](https://docs.google.com/spreadsheets/d/1ukyXgi_jRPeXj7EAST0IrnPfLOQ6xDBkcyAJY9N-Yb4/edit#gid=1117970540).

Points: 4

# How to claim to solve the issue

If you want to implement this function, please leave a comment in this issue like:

> I'd like to implement this function, please assign this issue to me.

**Comment by mucoban** [comment]
I'd like to implement this function, please assign this issue to me.

**Comment by deleteLater** [comment]
Thanks @mucoban 🤝  I've assigned this issue to you.

**Comment by mucoban** [comment]
I created the pr. Can you review?

**Comment by mucoban** [comment]
hi, I pushed a commit upon your comments
