### ISSUE TITLE
[Good First Issues]: Change "Feature flags and segments" to "Evaluate on flags and segments"

### ISSUE THREAD

**Issue by deleteLater** [featbit/featbit#337]
# Description
We propose to change the "Feature flags and segments" action in the End Users page to "Evaluate on flags and segments". The current name is confusing, and the new name is more accurate and informative.

Three tasks need to be done
- Change text from "Feature flags and segments" to "Evaluate on flags and segments"
- Remove the text "Feature flags and segments: " from the user segment flags drawer title
- Update the Chinese translation to `评估开关和用户组`

# Scope
- Service: UI
- Components: end user index and user segment flags drawer components
- Location: 
    - modules/front-end/src/app/features/safe/end-users/index
    - modules/front-end/src/app/core/components/user-segments-flags-drawer

# Screenshot
![image](https://user-images.githubusercontent.com/34052208/234816612-6ab6672a-fdf7-4948-8a8b-0d43afd367ab.png)
![image](https://user-images.githubusercontent.com/34052208/234817055-42b8617f-bef1-4ea5-9936-f41ae1e46d98.png)

# Setup dev environment

Please read the [doc](../blob/main/Development.md) to set up your development environment.

# Deadline

We usually give 2 weeks for a feature request, which means you have 2 weeks to implement the feature starting from the
day it is assigned to you. If you have any difficulties, please contact us
in [Slack](https://join.slack.com/t/featbit/shared_invite/zt-1ew5e2vbb-x6Apan1xZOaYMnFzqZkGNQ).

# How to implement

1. Fork the FeatBit repository.
2. Create a branch issues-{issues number}
3. Implement the task based on Description and Scope mentioned above.
4. Submit your PR

Make sure you complete the following tasks before submit your PR:

- merge featbit main branch into your working branch
- run `npm run i18n`
- commit **messages.xlf & messages.zh.xlf** file changes

# Contribution points

Each contribution counts a certain number of points, depending on its difficulty. Contributors earn the appropriate
points when the work is merged. Contribution points are used to describe the contributions that contributors have made.
They can also be used to receive rewards for community events. You can view the current community submissions on a
public [google sheet](https://docs.google.com/spreadsheets/d/1ukyXgi_jRPeXj7EAST0IrnPfLOQ6xDBkcyAJY9N-Yb4/edit#gid=1117970540).

Points: 4

# How to claim to solve the issue

If you want to implement this function, please leave a comment in this issue like:

> I'd like to implement this function, please assign this issue to me.

**Comment by fMoro1999** [comment]
I'd like to implement this function, please assign this issue to me.
