### ISSUE TITLE
[Good First Issues]: Refactor `EscapeRegex` Method

### ISSUE THREAD

**Issue by deleteLater** [featbit/featbit#338]
# Description

We plan to refactor the `EscapeRegex` method in our project's code base to improve its readability. This method will be called when we check if the user has permission to perform an action on a specific resource.

https://github.com/featbit/featbit/blob/a37477e6430474fcd3d9b88687f3fdb7c80769c8/modules/back-end/src/Domain/Resources/ResourceHelper.cs#L20-L23

Four tasks need to be done
- Move this method to a `StringHelper` class
- The original regex string is hard to read (too many backslash), use [verbatim string](https://learn.microsoft.com/en-us/dotnet/csharp/programming-guide/strings/#verbatim-string-literals) `@"([.*+?^=!:${}()|[\]/\\])"` and `@"\$1"` instead.
- Add a comment to explain the regular expression in this code (We suggest using ChatGPT or [regexr](https://regexr.com/) to explain this regex string)
- Add tests for `EscapeRegex` method (We suggest using ChatGPT to generate tests or test cases)

# Scope
- Service:API
- Location: modules/back-end/src/Domain/Resources/ResourceHelper.cs

# Deadline

We usually give 2 weeks for a feature request, which means you have 2 weeks to implement the feature starting from the
day it is assigned to you. If you have any difficulties, please contact us in [Slack](https://join.slack.com/t/featbit/shared_invite/zt-1ew5e2vbb-x6Apan1xZOaYMnFzqZkGNQ).

# How to implement

1. Fork the FeatBit repository.
2. Create a branch issues-{issues number}
3. Implement the task based on Description and Scope mentioned above. 
4. Submit your PR

# Contribution points

Each contribution counts a certain number of points, depending on its difficulty. Contributors earn the appropriate
points when the work is merged. Contribution points are used to describe the contributions that contributors have made.
They can also be used to receive rewards for community events. You can view the current community submissions on a
public [google sheet](https://docs.google.com/spreadsheets/d/1ukyXgi_jRPeXj7EAST0IrnPfLOQ6xDBkcyAJY9N-Yb4/edit#gid=1117970540).

Points: 8

# How to claim to solve the issue

If you want to implement this function, please leave a comment in this issue like:

> I'd like to implement this function, please assign this issue to me.

**Comment by Exilon24** [comment]
I'd like to solve this issue.

**Comment by deleteLater** [comment]
Thanks @Exilon24, we've assigned this issue to you :smile:
