### ISSUE TITLE
[Bug]: Content of number input is not vertically centered

### ISSUE THREAD

**Issue by cosmos-explorer** [featbit/featbit#347]
## Describe the bug
The content of number input is for feature lflag percentage rollout is not vertically centered

## To Reproduce
1. Targeting page of a feature flag
2. Set default serve to percentage rollout

![image](https://github.com/featbit/featbit/assets/88151306/ffb11590-5949-4c0b-b28c-e9c5efeab009)

## Expected behavior
The content should be vertically centered

![image](https://github.com/featbit/featbit/assets/88151306/063a8bee-eed3-442d-85f1-d7fc7299b4b5)

# Scope
- Service: UI
- File to change: modules/front-end/src/app/core/components/find-rule/serve/serve.component.less
- Fix style for **.ant-input-number**

## Setup dev environment

Please read the [doc](../blob/main/Development.md) to set up your development environment.

# How to implement

1. Fork the FeatBit repository.
2. Create a branch issues-{issues number}
3. Implement the task based on Description and Scope mentioned above.
4. Submit your PR

## Contribution points

Each contribution counts a certain number of points, depending on its difficulty. Contributors earn the appropriate
points when the work is merged. Contribution points are used to describe the contributions that contributors have made.
They can also be used to receive rewards for community events. You can view the current community submissions on a
public [google sheet](https://docs.google.com/spreadsheets/d/1ukyXgi_jRPeXj7EAST0IrnPfLOQ6xDBkcyAJY9N-Yb4/edit#gid=1117970540).

Points: 2

## How to claim to solve the issue

If you want to implement this function, please leave a comment in this issue like:

> I'd like to implement this function, please assign this issue to me.

FeatBit community will assign the issue to you on time.

**Comment by Shubh8899** [comment]
I would like to pick this one up.

**Comment by cosmos-explorer** [comment]
Thanks @Shubh8899 , we've assigned this issue to you 😄

**Comment by Shubh8899** [comment]
@cosmos-explorer  can you explain a bit more like how vertically centered should the input be? Maybe screenshot of expected output could help. Thanks

**Comment by cosmos-explorer** [comment]
@Shubh8899 just added a screenshot to the Expected behavior
