### ISSUE TITLE
[Bug]: In the feature flag list, I'm struggling to comprehend the JSON and lengthy string variants.

### ISSUE THREAD

**Issue by cosmic-flood** [featbit/featbit#356]
### What happened?

In the feature flag list, I'm struggling to comprehend the JSON and lengthy string variants.

The issue is, when there's a single lengthy string or JSON variant, the complete information isn't displayed when I hover over the variant with the mouse.
![image](https://github.com/featbit/featbit/assets/68597908/1bc2cce0-472b-4294-81fb-79a2e9397691)

### To Reproduce

1. Create a feature flag
2. Change variant as Json format
3. Input a Json content (more than 30 characters)
4. Come back to feature flag list, you will see the problem

### Expected behavior

When I hover over the variant with the mouse, please ensure that the complete information is displayed.

Alternatively, consider giving each variant an easy-to-understand name. Display this name by itself, or alongside the variant content.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by mucoban** [comment]
hi @cosmic-flood ,  I can fix this bug. Can you assign it to me?

**Comment by deleteLater** [comment]
Thanks @mucoban, I've assigned this issue to you 🍉
