### ISSUE TITLE
[Bug]: The get started page has made the environment switch corner invisible.

### ISSUE THREAD

**Issue by cosmic-flood** [featbit/featbit#368]
### What happened?

The new get started module page has made the environment change module section in my top right corner invisible.

![image](https://github.com/featbit/featbit/assets/68597908/4292b55f-cd74-483a-9bc0-a03351afc7b0)

Browser: Chrome

My laptop: Dell XPS 17, 9720. Made for developer
Resolution: 250% (recommended)   3840 x 2400 (recommended)

### To Reproduce

Please adjust your browser size to mimic the screen dimensions I've mentioned above in order to replicate the issue

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Shubh8899** [comment]
I would like to pick this up.

**Comment by deleteLater** [comment]
Thanks @Shubh8899, I've assigned this issue to you 🍀
