### ISSUE TITLE
[Bug]: Documentation Beta Testing page copied from LaunchDarkly

### ISSUE THREAD

**Issue by kanadaj** [featbit/featbit#409]
### What happened?

The docs seems to have a page that got copy-pasted from LaunchDarkly without editing...

### To Reproduce

1. Go to https://docs.featbit.co/docs/getting-started/5.-how-to-guides/beta-testing-qualitative-feedback
2. Search for LaunchDarkly
3. Yep.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by cosmos-explorer** [comment]
Just fixed thank you
