### ISSUE TITLE
Feature Suggestion: Feature Flags Import/Export

### ISSUE THREAD

**Issue by yuriirud** [featbit/featbit#496]
Hey!

I don't see a neat way to export feature flags between projects. The thing I'm trying to solve is that we plan to have 2 separate instances of FeatBit - one for dev/stage, one for prod. And easy way to just copy whatever PO has came up with and paste it between instances would be so much easier.

Or we can try to solve with from different angle - how we can specify where dev or prod environments APIs are allocated? So I have dev on dev.mycloud.com and prod on prod.mycloud2.com and those are both managed from the same CMS on dev

Thanks!

**Comment by cosmic-flood** [comment]
Hi @yuriirud 

Thank you for the suggestion. You can maybe try this tutorial way:

https://docs.featbit.co/docs/relay-proxy/relay-proxy

You can think of each environment (dev/test/pro) as an agent. You can sync feature flags and segment data from dev to pro, as same as sync data from a hosted FeatBit service to one of its agents.

If you want to also sync end user data, you can try with this tutorial: 

https://docs.featbit.co/docs/data-import-and-export/end-users 

I hope this can help you, please let me know if the above solution doesn't fit your needs.
