### ISSUE TITLE
[Bug][Good First Issues]: Inconvinient to overview my feature flag configuration

### ISSUE THREAD

**Issue by small-duble** [featbit/featbit#506]
### What happened?

We have a lot of user segments, we have used it to do some beta testing, experimental features and also AB testing.
I am trying to use FeatBit to solve the orthogonality requirement of our AB testing.

But we all find it very inconvenient that we can't easily see our segment's name.  As the figure below shows, I can't easily see the difference between each segment.

I'd say that the length of the segment name can easily exceed the display limit you set by default.

I hope you can solve this little problem in the near future.

:D

### To Reproduce

![image](https://github.com/featbit/featbit/assets/68597908/14b2db6f-f7a8-4dc3-9024-4303a3cf75d7)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by cosmic-flood** [comment]
Thank you for the feedback, we will improve this experience in near future.

**Comment by mucoban** [comment]
Hi I would like to solve this issue, can you assign that to me  @cosmic-flood

**Comment by cosmic-flood** [comment]
@mucoban Yes, I assigned it to you!
