### ISSUE TITLE
[Bug]:  DataDog webhook sends only POST request for feature flags trigger

### ISSUE THREAD

**Issue by cosmic-flood** [featbit/featbit#509]
I am testing with the DataDog Webhook integration. I want to trigger a feature flag to turn off after DataDog monitor sent a critical alert. But DataDog only sends POST requests to the trigger URL. But FeatBit's trigger URL only accepts PUT requests.

https://docs.datadoghq.com/integrations/webhooks/

![image](https://github.com/featbit/featbit/assets/68597908/399fd9c9-1f2b-46e8-9c64-b0e6f91262a3)

Can you add support for POST request to URL? Thanks.

**Comment by deleteLater** [comment]
Completed in #511
