### ISSUE TITLE
[Bug]: Social links not working in the footer of the website.

### ISSUE THREAD

**Issue by niranjan-kurhade** [featbit/featbit#524]
### What happened?

A bug happened! The social links of Twitter, YouTube, Github, and Slack aren't working in the footer of the website.
They are working in the mobile view but not in the desktop view.

### To Reproduce

1. Go to... https://www.featbit.co/
2. And scroll down to its footer.

### Expected behavior

The icons/buttons should redirect to their proper links when clicked on the website on the desktop. 

### Additional context

![image](https://github.com/featbit/featbit/assets/97905637/29d75091-06c5-4128-9694-540d786e1c7e)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by niranjan-kurhade** [comment]
Please assign me this issue. I would like to work on it and fix this.

**Comment by deleteLater** [comment]
cc @cosmic-flood

**Comment by cosmic-flood** [comment]
Hi @niranjan-kurhade 

Thank you for your feedback. I left you a message on Slack. Actually, the homepage project is independent and in a private repository. 

It's kind of hard to make the project public today.  I don't think I can allow you to contribute to it. But thanks for the question. Much love to your contribution.

**Comment by cosmic-flood** [comment]
Fixed in private repo for home page. Thank you again @niranjan-kurhade
