### ISSUE TITLE
[BUG] The "Is One Of" condition in the form is not functioning properly, as illustrated in my screen capture.

### ISSUE THREAD

**Issue by cosmic-flood** [featbit/featbit#550]
The "Is One Of" condition in the form is not functioning properly, as illustrated in my screen capture. **The experience is just far away from other feature flag tools.**

1. The entire content of my input should be visible.

![image](https://github.com/featbit/featbit/assets/68597908/1a1888f0-7be5-4f7e-90f8-da3b39408885)

![image](https://github.com/featbit/featbit/assets/68597908/9715b1cc-317f-48c3-bf81-1208370075ae)

2. My text should not be obscured by the dropdown arrow.

![image](https://github.com/featbit/featbit/assets/68597908/f109982f-0e8d-49dc-804a-9bbf7906822e)

Browser :
 - Edge & Chrome

**Comment by deleteLater** [comment]
We can use this: https://ng.ant.design/components/select/en#components-select-demo-automatic-tokenization

**Comment by qixiaojian310** [comment]
I'd like to implement this function, please assign this issue to me.
