### ISSUE TITLE
Feature Suggestion: Client-Side SDK for .NET

### ISSUE THREAD

**Issue by SamKr** [featbit/featbit#574]
**Is your feature request related to a problem? Please describe.**
There's currently no SDK for client-side thick applications, eg. WPF or WinForms. Currently I have to use the REST API, as there's only the [server-side SDK](https://github.com/featbit/featbit-dotnet-sdk).

**Describe the solution you'd like**
A Client-Side SDK for .NET.

**Describe alternatives you've considered**
FeatBit's [REST API](https://docs.featbit.co/sdk/retrieve-feature-flags-with-api#client-side).

**Additional context**
Discussed in issue [#14 Client-Side SDK](https://github.com/featbit/featbit-dotnet-sdk/issues/14) in the server-side SDK repo.

**Is this feature something you're interested in working on?**
I can at the very least help test, as I have a WPF application in which I'm planning on using it. I don't have too much spare time, but if there are specific tickets I can assist with I don't mind writing a few PRs.

**Comment by cosmic-flood** [comment]
Status Changed: In Progress

https://github.com/orgs/featbit/projects/6

**Comment by wss-alubic** [comment]
+1 to this.  I'm writing a Blazor WebAssembly app that would benefit from a .NET Client SDK.

**Comment by cosmic-flood** [comment]
> +1 to this. I'm writing a Blazor WebAssembly app that would benefit from a .NET Client SDK.

I have played with Blazor WebAssembly for a side project, but I am not very familiar with it. Hope you can share your experience about it. I'm making a very simple client SDK now, I'm testing in .NET Maui project, it's similar to WPF.

**Comment by cosmic-flood** [comment]
I am working on a .NET Client SDK, which I hope will be compatible with .NET MAUI, Console Apps, Blazor WebAssembly, WPF, and so on. Here's a video that I just tested with Blazor. Fingers crossed


https://github.com/featbit/featbit/assets/68597908/0a7006f4-2dad-4fe8-a617-abdb448864b5

**Comment by SamKr** [comment]
Awesome work @cosmic-flood, looking good :)

**Comment by cosmic-flood** [comment]
https://github.com/featbit/featbit/assets/68597908/ee68cd0f-cb5b-4714-9dc4-a5a462eec3cb

First Impressions of Love with FeatBit's .NET Client SDK on .NET MAUI. (Polling Mode)

P.S.: : Successfully tested on Console, WPF and Blazor WebAssembly.

**Comment by deleteLater** [comment]
Hi @SamKr @wss-alubic, we've released FeatBit.ClientSdk v1.0.0! You can visit [the repo](https://github.com/featbit/featbit-dotnet-client-sdk) and follow the README to get started.

**Comment by SamKr** [comment]
Looks perfect, and a very thorough readme as well. Thanks so much for this ❤️

**Comment by cosmic-flood** [comment]
> Looks perfect, and a very thorough readme as well. Thanks so much for this ❤️

Hi @SamKr 

We're currently gathering user feedback to help improve our product and secure additional funding. If it's not too much trouble, could you please share a short story about your experiences—both good and bad—with FeatBit? If you could also mention your team, product, or company, that would be perfect.

Please send your stories to our email at contact@featbit.co

**Comment by SamKr** [comment]
Of course, glad I can help. Will send a mail from my work email in the coming days.
