### ISSUE TITLE
[BUG] If the variation name is not short, we won't be able to see the full name.

### ISSUE THREAD

**Issue by cosmic-flood** [featbit/featbit#582]
The screenshot below describe the bug clearly.

- ChatGPT 4 32k
- ChatGPT 3.5 Turbo 16k
- OpenChat 3.5
- ...

![image](https://github.com/featbit/featbit/assets/68597908/6484675c-4df2-4e54-8466-15cc7848dc48)

**Comment by deleteLater** [comment]
Adding a tooltip for the variation name would be useful. And for the copy and expand button, we just need one. For example, we left the expand button, and enabling users to copy the value by clicking it. @cosmos-explorer

**Comment by qixiaojian310** [comment]
I'd like to implement this function, please assign this issue to me.

**Comment by cosmos-explorer** [comment]
Fixed in https://github.com/featbit/featbit/pull/616
