### ISSUE TITLE
[Good First Issues]: Add Connection Information to Featbit Eval Server logs 

### ISSUE THREAD

**Issue by wss-rbrennan** [featbit/featbit#604]
# Description
Currently, the logging functions defined in `ConnectionHandler.Log.cs` class only log the `connectionId`, and error message if there was one, and in some cases an event.

`connectionId` is not very helpful in tracking down which client interaction caused the log message.

The logs should include the ~~project id~~, the environment id, client IP address, and client hostname if availabe.

With this information system admins will be able to find the project, environment, and client associated with a log message

The client IP address can be obtained in 'StreamingMiddleware.cs' by capturing one of the following (see references)

`context.Connection.RemoteIpAddress`
`HttpContext.GetServerVariable("HTTP_X_FORWARDED_FOR");`
`Request.Headers["CF-CONNECTING-IP"];`

The hostname can be retrieved with
`Dns.GetHostEntry(<ip address variable>).HostName;`

These should be passed to `RequestHandler` and added to the `Connection` Object, Connections should not fail or throw exceptions if the client IP, or hostname are not retrieveable, they should instead be empty strings.

~~The projectId can be obtained using the MongoDbClient with a query similar to the following~~

~~The projectId retrieval ideally will be feature gated using an environment variable such as `EVAL_LOG_PROJECT_ID` with a default of false. this is to avoid adding potential latency to the initial websocket connection while this feature matures.~~

`LoggerMessage` Attriubutes and associated Funcitons in `ConnectionHandler.Log.cs` should be updated to include `envId`, ~~`projectId`~~, `clientId`, and `clientHostname`

Refactor function callers to include this information.

#References

https://juldhais.net/how-to-get-client-ip-address-and-location-information-in-asp-net-core-c2bb50e689c3

# Scope

Evaluation Server

# Screenshot

# Setup dev environment

Please read the [doc](../blob/main/Development.md) to set up your development environment.

# Deadline

We usually give 2 weeks for a feature request, which means you have 2 weeks to implement the feature starting from the
day it is assigned to you. If you have any difficulties, please contact us in [Slack](https://join.slack.com/t/featbit/shared_invite/zt-1ew5e2vbb-x6Apan1xZOaYMnFzqZkGNQ).

# How to implement

1. Fork the FeatBit repository.
2. Create a branch issues-{issues number}
3. Implement the task based on Description and Scope mentioned above.
4. Submit your PR

If the feature is UI related, make sure you complete the following tasks before submit your PR:

- merge featbit main branch into your working branch
- run `npm run i18n`
- commit **messages.xlf & messages.zh.xlf** file changes (if any)

# Contribution points

Each contribution counts a certain number of points, depending on its difficulty. Contributors earn the appropriate
points when the work is merged. Contribution points are used to describe the contributions that contributors have made.
They can also be used to receive rewards for community events. You can view the current community submissions on a
public [google sheet](https://docs.google.com/spreadsheets/d/1ukyXgi_jRPeXj7EAST0IrnPfLOQ6xDBkcyAJY9N-Yb4/edit#gid=1117970540).

Points: 4

# How to claim to solve the issue

If you want to implement this function, please leave a comment in this issue like:

> I'd like to implement this function, please assign this issue to me.

**Comment by deleteLater** [comment]
Regarding the retrieval of the projectId, I'm working on another PR related to this. In that PR, I'll store the environment secret in Redis, with the key being `featbit:secret:{the-secret-string}`, and the value being a list of hash entries.

The code looks like this:

```csharp
public async Task UpsertSecretAsync(Guid envId, Secret secret)
{
    var key = RedisKeys.Secret(secret.Value);
    var fields = new HashEntry[]
    {
        new("envId", envId.ToString()),
        new("envKey", "the-env-key"),
        new("projectId", "the-projectId"),
        new("projectKey", "the-project-key"),
        new("type", secret.Type)
    };

    await _redis.HashSetAsync(key, fields);
}
```

Then, on the evaluation server side, I can retrieve all this secret information from Redis for request validation.

- If the secret is not found in Redis, the request will be rejected.
- If the secret type is inconsistent (for the server-side SDK, the secret type should be "server", and for the client-side SDK, the secret type should be "client"), the request will be rejected.

Since I have all this information, I'll store it in the `Connection` class. Then we can use `connection.Secret.ProjectId` to get the project ID. also, maybe it would be better to use `envKey` and `projectKey` in the logs as it is easier to read.

**Comment by wss-alubic** [comment]
+1 to using the keys over the IDs.  It'd be easier to follow when triaging issues using the logs.

**Comment by wss-rbrennan** [comment]
I removed the projectId requirements from this issue so we don't duplicate the work that @deleteLater is doing to retrieve project information. It can can bee added as a different issue when the data is available in redis.
