### ISSUE TITLE
[BUG] Cannot login on fresh install

### ISSUE THREAD

**Issue by abbasmhd** [featbit/featbit#608]
I followed the instructions to run in the readme to run featbit locally with docker on Windows

When I tried to log in with the provided credential I get this error 
`{"success":false,"errors":["EmailPasswordMismatch"],"data":null}`

![2024-03-16_09h43_19](https://github.com/featbit/featbit/assets/1510389/f340973a-ce2a-4bac-9394-31de956fa16a)
![2024-03-16_09h46_54](https://github.com/featbit/featbit/assets/1510389/69e405fa-a109-4ab8-b387-ef321758d4ac)

**Comment by deleteLater** [comment]
Hi @abbasmhd , Can you share the Api service logs?

**Comment by abbasmhd** [comment]
Unfortunately, none of the solutions in the discussion do not work for me, 
I have done some debugging, and it looks like the `workspaceId is null` 
![image](https://github.com/featbit/featbit/assets/1510389/90044bca-83e3-4639-be1d-d3957d108913)

**Comment by cosmic-flood** [comment]
> Unfortunately, none of the solutions in the discussion do not work for me, I have done some debugging, and it looks like the `workspaceId is null` ![image](https://private-user-images.githubusercontent.com/1510389/313434843-90044bca-83e3-4639-be1d-d3957d108913.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTA2NDg5MjgsIm5iZiI6MTcxMDY0ODYyOCwicGF0aCI6Ii8xNTEwMzg5LzMxMzQzNDg0My05MDA0NGJjYS04M2UzLTQ2MzktYmUxZC1kMzk1N2QxMDg5MTMucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDMxNyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAzMTdUMDQxMDI4WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9M2FhOTNkNTc0NWU3NmMzOTQxZGQ3MGUwMTNhMzBjYTdhMjdhODg5ZTgxMDJlMzRjYmRkMGUwMDgwZWJkMDU1NiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.B9Sj4n840xZ5QOyfiu6f4NpkY11UeXyfwpOW6gKRzN0)

@abbasmhd 

Can you try running the following script to initialize MongoDB?

https://github.com/featbit/featbit/blob/main/infra/mongodb/docker-entrypoint-initdb.d/init.js

Normally, the script runs automatically during the installation of Docker Compose, but it seems that it wasn't successful.


> If it still doesn't work. Try opening the browser in private mode and try again.

**Comment by abbasmhd** [comment]
That worked and solved my issue thank you
