### ISSUE TITLE
[Bug]: fresh install login issue

### ISSUE THREAD

**Issue by myskamartin** [featbit/featbit#621]
### What happened?

Based on the instructions in the documentation I have started Featbit via `docker-compose` on MacOS. I had to change the port for API from `5000` to `5001`, cause on MacOS port `5000` is taken by AirPlay.

All containers start without a problem, but I am not able to log in to the UI with the default credentials that are in the documentation.
In the console, I am getting the CORS error which I think is the cause of the problem.
Any ideas are more than welcome.

![Screenshot 2024-03-28 at 18 36 51](https://github.com/featbit/featbit/assets/119139044/9a2f9049-0aa4-4232-a34b-68cafb9f8246)
![Screenshot 2024-03-28 at 18 37 29](https://github.com/featbit/featbit/assets/119139044/f1a49bb7-9322-4da9-af84-492b5d7eed6a)
![Screenshot 2024-03-28 at 18 37 35](https://github.com/featbit/featbit/assets/119139044/c11d5d72-0098-4430-9a05-f3a60dcb3652)
![Screenshot 2024-03-28 at 18 37 59](https://github.com/featbit/featbit/assets/119139044/21a91a04-aff7-487f-8ade-3cc04b49412c)
![Screenshot 2024-03-28 at 18 38 06](https://github.com/featbit/featbit/assets/119139044/6cb71728-cb67-45f9-8a16-afd47ce03df2)
![Screenshot 2024-03-28 at 18 38 10](https://github.com/featbit/featbit/assets/119139044/2902d6d9-a25e-463e-b182-485bd8e03495)

### To Reproduce

1. `git clone https://github.com/featbit/featbit`
2. cd `featbit`
3. Updated API port from `5000` to `5001` in `docker-compose.yml`
4. `docker-compose up -d`

### Expected behavior

Successfully login to the UI

### Additional context

I checked the issues and followed the recommendation from this one https://github.com/featbit/featbit/issues/608 to manually initialize MongoDB. But the CORS error persisted.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by deleteLater** [comment]
Hi @myskamartin, can you try

- `curl http://localhost:5001/health/liveness` to make sure the api service is started successfully
- check the api service logs, any exceptions?

**Comment by deleteLater** [comment]
And to figure out why the preflight request fails, try the following command in bash:

```bash
curl -v 'http://localhost:5001/api/v1/user/has-multiple-workspaces' \
  -X 'OPTIONS' \
  -H 'Access-Control-Request-Headers: authorization,content-type,organization,workspace' \
  -H 'Access-Control-Request-Method: POST' \
  -H 'Origin: http://localhost:8081'
```

**Comment by myskamartin** [comment]
Hi @deleteLater, and thanks for your reply.

The API server has started successfully:
```bash
[root@ip-10-98-170-245 ~]# curl  http://localhost:5000/health/liveness
Healthy
```
I don't see any exception in the API logs that would raise my attention, everything looks in order.

But checking why the preflight request fails reveals the `204 No Content` (full output below)
```bash
[root@ip-10-98-170-245 featbit]# curl -v 'http://localhost:5000/api/v1/user/has-multiple-workspaces' \
> -X 'OPTIONS' \
> -H 'Access-Control-Request-Headers: authorization,content-type,organization,workspace' \
> -H 'Access-Control-Request-Method: POST' \
> -H 'Origin: http://localhost:8081'
*   Trying 127.0.0.1:5000...
* Connected to localhost (127.0.0.1) port 5000> OPTIONS /api/v1/user/has-multiple-workspaces HTTP/1.1
> Host: localhost:5000
> User-Agent: curl/8.3.0
> Accept: */*
> Access-Control-Request-Headers: authorization,content-type,organization,workspace
> Access-Control-Request-Method: POST
> Origin: http://localhost:8081>
< HTTP/1.1 204 No Content
< Date: Fri, 29 Mar 2024 22:04:08 GMT
< Server: Kestrel
< Access-Control-Allow-Headers: authorization,content-type,organization,workspace
< Access-Control-Allow-Methods: POST
< Access-Control-Allow-Origin: *
<
* Connection #0 to host localhost left intact
```

Any further help is much appreciated.

FYI:  I have started a new installation on Amazon Linux 2023 instance, thus I am no longer using port `5001`

**Comment by cosmic-flood** [comment]
Try running the following script in mongodb and see what happens?

https://github.com/featbit/featbit/blob/main/infra/mongodb/docker-entrypoint-initdb.d/init.js

**Comment by myskamartin** [comment]
Hi @cosmic-flood,

Running the script will seed the database, but the issue remains and I don't see exceptions in the logs either.

**Comment by deleteLater** [comment]
The preflight request returns 204 indicating that there is no CORS issue. Our Api service has request logging enabled by default, so if you refresh your browser, you'll see a browser request log like this one. Can you see these logs?
 
![image](https://github.com/featbit/featbit/assets/34052208/90ad255b-1ef3-4154-a0ca-d524db66d886)

**Comment by myskamartin** [comment]
No, I don't see that in the logs at all.

I am a little bit confused. Given the `docker-compose` configuration and that I can reach the `API` container from the `UI` container, what else do I need to do to reach the API service?

Again, I am not changing the configuration at all to be clear on this one.

**Comment by deleteLater** [comment]
Ok, so **the question is why requests sent from the browser are not reaching the API service**. To be clear, the **request was sent from the browser, not the UI service**, so you need to make sure that you can access the API service from the machine that is accessing the UI.

**Comment by deleteLater** [comment]
Close this issue as there is no further information. Feel free to reopen it if you have any questions. @myskamartin

**Comment by ddenev** [comment]
found it. run this command in the `mongo` container:
`mongosh -u admin -p password < init.js`
