### ISSUE TITLE
Feature Suggestion: Filling variation values according to variation type in the create feature flag page

### ISSUE THREAD

**Issue by mucoban** [featbit/featbit#650]
**Problem**
When creating a feature flag, change variation type from boolean to string, all variation values stay as 'true'. This can be confusing for users.
<img width="605" alt="image" src="https://github.com/user-attachments/assets/32c7be22-58fd-423b-9ce6-86efe3e6c56f">

**Solution**
We can adjust the frontend as variation values be filled correctly upon the change of variation type in create feature flag page.
It can be like
When variation type is selected as 
boolean, 1st variation value is to be true and 2nd is to be false (it is like that now already)
<img width="547" alt="image" src="https://github.com/user-attachments/assets/5b5536a7-200c-476c-9fe7-822cdbb0b989">

string, all variation values are to be their variation names in lowercase
<img width="553" alt="image" src="https://github.com/user-attachments/assets/c12a1fe4-75a2-4184-b6f8-147a82f3d2f7">

number,  all variation values are to be the numbers in their variation names
<img width="550" alt="image" src="https://github.com/user-attachments/assets/f797ee8b-889f-4494-a5ae-103c3b1b258d">

json,  all variation values are to be the {} or []
<img width="522" alt="image" src="https://github.com/user-attachments/assets/fb84dc2c-dbc9-4ac5-a937-ce222a3748fe">

We can also update variation values while user typing in variation names,  according to above rules to help to user.

I can do this feature if I am assigned to it.

**Comment by mucoban** [comment]
Can you assign this issue to me @cosmos-explorer

**Comment by cosmic-flood** [comment]
We assigned this task to you @mucoban Thank you.
