### ISSUE TITLE
[Bug]: Experimentation line chart shows wrong dates

### ISSUE THREAD

**Issue by ghelyar** [featbit/featbit#652]
### What happened?

The dates on the experimentation line chart seem to be wrong.

It looks like the month value is coming from the minute value (`MM` vs `mm` perhaps) but I don't know where the day is coming from, and the year is missing. I was just trying out the product locally with the docker compose quick start and noticed this.

![image](https://github.com/user-attachments/assets/a8f15a24-a85c-4287-a576-1a0d46504984)

As I refresh, the time component is updated correctly but the month changes with the minutes
![image](https://github.com/user-attachments/assets/74bd2d4f-bc5a-47c6-b383-4d86d6e237c3)

### To Reproduce

1. start featbit locally
   ```
   git clone https://github.com/featbit/featbit
   cd featbit
   docker compose up
   ```
2. create a feature flag with an experiment
3. use the SDK to read a feature flag and track an event for the metric of the experiment
4. go to the experiment in the FeatBit UI
5. click "show chart"

### Expected behavior

The dates on the line chart should be valid dates and match the dates in the table above it

### Additional context

docker container `featbit/featbit-ui:3.3.5` (`latest` at the time)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by cosmic-flood** [comment]
Thanks for the feedback, we will fix it.
