### ISSUE TITLE
[BUG] division by zero on numeric metrics

### ISSUE THREAD

**Issue by ghelyar** [featbit/featbit#654]
**Describe the bug**
When creating a numeric metric with one tracked event in each variation, and then checking the experiment results, data analytics server throws a division by zero error

**To Reproduce**
1. quick start - clone the `featbit/featbit` repo and `docker compose up`
2. go to `http://localhost:8081/`, log in and create a project
3. create a boolean feature flag that is on but defaults to false
4. add a targeting rule so that a specific user will get served true (e.g. "if keyId equals t serve true")
   ![image](https://github.com/user-attachments/assets/40d05e37-8b78-433d-8196-5b87ab70c254)
5. add a numeric metric
7. create an experiment using the feature flag and the metric
8. start the experiment
   ![image](https://github.com/user-attachments/assets/e2f7a605-d71b-42b5-a1e0-5f4cd059e2c9)
9. evaluate the flags using an SDK so that one user gets true, and one gets false, and both track the metric e.g.
   ```csharp
   var client = new FbClient(FbOptions.Default(sdkKey));

   var user1 = FbUser.Builder("f").Build();
   client.BoolVariation("test", user1, false);
   client.Track(user1, "event", 2.0);

   var user2 = FbUser.Builder("t").Build();
   client.BoolVariation("test", user2, false);
   client.Track(user2, "event", 1.0);

   await client.CloseAsync();
   ```
10. view the experiment in the UI, and note that it shows no data, and buttons like "stop experiment" do not work
   ![image](https://github.com/user-attachments/assets/986c767c-1b0a-432b-b1c6-b9e781044657)
11. check the docker compose logs for `da-server-1`
   ```
   [2024-08-01 09:18:29,114] ERROR in views: unexpected error occurs: float division by zero
   Traceback (most recent call last):
     File "/featbit_da/app/experimentation/views.py", line 25, in get_result
       data = analyze_experiment(Experiment.from_properties(json.loads(json_str)))
     File "/featbit_da/app/experimentation/models/experiment/trends_experiment_result.py", line 37, in analyze_experiment
       res = [OnlineTTest(control=control,  # type: ignore
     File "/featbit_da/app/experimentation/models/experiment/trends_experiment_result.py", line 37, in <listcomp>
       res = [OnlineTTest(control=control,  # type: ignore
     File "/featbit_da/app/experimentation/models/experiment/experiment_types.py", line 320, in get_result
       p_value = self.p_value
     File "/featbit_da/app/experimentation/models/experiment/experiment_types.py", line 271, in p_value
       return 2 * (1 - t_test.cdf(np.abs(self.t_statistic), self.df))  # type: ignore
     File "/featbit_da/app/experimentation/models/experiment/experiment_types.py", line 267, in df
       return (vnt + vnc)**2 / (vnt**2 / (nt - 1) + vnc**2 / (nc - 1))
   ZeroDivisionError: float division by zero
   ```

**Expected behavior**
This should show the correct number of events in each variation, with the average values for each

**Additional context**
FeatBit version 3.3.5

**Comment by cosmic-flood** [comment]
Thanks for the detailed bug report. We will take a look and fix it.
