### ISSUE TITLE
Can rollout percentage dispatch by nothing?

### ISSUE THREAD

**Issue by kobe2000** [featbit/featbit#655]
Hi,

My application support anonymous visit. I did not find a way to disptach requests only by percentage.

Thanks

**Comment by cosmic-flood** [comment]
![image](https://github.com/user-attachments/assets/dd8dff46-1afe-4d5e-8c7c-cffacf63907a)

Can this help you? You can give each anonymous visit an anonymous random id.

**Comment by kobe2000** [comment]
> ![image](https://private-user-images.githubusercontent.com/68597908/355072831-dd8dff46-1afe-4d5e-8c7c-cffacf63907a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjI4NTQ5NzMsIm5iZiI6MTcyMjg1NDY3MywicGF0aCI6Ii82ODU5NzkwOC8zNTUwNzI4MzEtZGQ4ZGZmNDYtMWFmZS00ZDVlLThjN2MtY2ZmYWNmNjM5MDdhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MDUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODA1VDEwNDQzM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWY3M2Y5N2M5NDY0YzUzYTMzMDVkOWUxYjMzOGM2MTIzMjMxNzlmM2VjZjQ2ZDIzZThjOTg1Njc1NWYzMWYyMDImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.phdBgbhsbkjM_nbePiypLe9oX147t_bztvC-Xv8qH_4)
> 
> Can this help you? You can give each anonymous visit an anonymous random id.

Yes. But I think that's a general requirements which can be handled by the product, isn't it?
