### ISSUE TITLE
[Bug]: .Net Core 8 treat empty strings as null for non-nullable reference types

### ISSUE THREAD

**Issue by cosmos-explorer** [featbit/featbit#667]
### What happened?

There appears to be a problem with a brand new install of featbit using docker compose. If I take the current repo from github, and run docker compose -f docker-compose.yml up -d, it sets me up a brand new installation. I can login using the test account, and set up the organisation, project and environment. However, from there, all search pages fail with an error similar to the following: 
```json
{
    "type": "https://tools.ietf.org/html/rfc9110#section-15.5.1",
    "title": "One or more validation errors occurred.",
    "status": 400,
    "errors": {
        "Name": [
            "The Name field is required."
        ]
    },
    "traceId": "00-eee64a4a3881f046919cf9f6249bd495-6e218a04cbeecfc1-00"
}
```

### To Reproduce

1. Go to feature flags list page, an error will occur

### Expected behavior

There should be no error

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by deleteLater** [comment]
Caused by #664
