### ISSUE TITLE
Feature Suggestion: Limit Webhooks to Specific Feature Flags

### ISSUE THREAD

**Issue by drewsteinacher** [featbit/featbit#678]
**Is your feature request related to a problem? Please describe.**
My team uses a [Webhook](https://docs.featbit.co/integrations/webhooks) to send notifications to a Teams channel when only a _specific_ feature flag is toggled. Note that Webhooks fire for _all_ matching feature flag events and segments.

The only way I was able to implement this was by making clever use of Handlebars.js templating to only send an Adaptive Card body if `data.object.key` was the desired feature flag key, and an empty JSON body otherwise:
```
{
   {{#eq data.object.key "desired-key"}}
   // Desired Adaptive Card body goes here
   {{/eq}}
}
```

The empty JSON body is required, since this body must be valid JSON, or the Webhook form will not submit.
* [Frontend requirement](https://github.com/featbit/featbit/blob/065f9d040853fd66f16589509ef5793948acea17/modules/front-end/src/app/core/components/webhook-drawer/webhook-drawer.component.ts#L132-L138)
* [Backend requirement](https://github.com/featbit/featbit/blob/065f9d040853fd66f16589509ef5793948acea17/modules/back-end/src/Infrastructure/Webhooks/WebhookSender.cs#L40C13-L40C41)

When the empty JSON body is sent, the webhook returns a 400-level response (due to it not being a valid Adaptive Card), and no notification is sent, thus having the desired behavior.

However, due to the [impending MS Teams Connectors deprecation](https://devblogs.microsoft.com/microsoft365dev/retirement-of-office-365-connectors-within-microsoft-teams/), we have had to change how we send these notifications.
Our new in-house solution does not behave the same with the empty body and will send a "blank" notification in this case, and will otherwise send some kind of notification _no matter what body it receives_. This means that it would spam our Teams channel with a notification whenever _any_ feature flag was enabled/disabled. Due to internal requirements, this behavior _will not be changed_, meaning my previous templating-based solution will not work. 

There needs to be some way to limit Webhooks from firing for some feature flags on the FeatBit side that doesn't involve creating extra notification-only environments (which would cause clutter and confusion and has been deemed as an unacceptable solution by my team).

**Describe the solution you'd like**
I can think of a few that would be acceptable, listed in no particular order:
1. **Add an optional "Feature Flags" chips/multi-select input under the "Scopes" section of the Webhook editing pane**
- This naturally extends the existing "Project" and "Environments" that are already there.
- Downside is that the UI might not look great/clear without significant restyling, as this is already a narrow pane and each Scope takes a full line.
- Unclear if a whitelist or blacklist or both would be clear/appropriate.
- This feature seems to exist in other feature flag systems.

2. **Add an optional whitelist and/or blacklist text field for matching on the key for a Feature Flag or Segment**
- Probably should only be enabled if a Feature Flag or Segment event is selected, respectively.
- Unclear if this should accept any of the following:
   - A delimited list of hard-coded keys like `some-key; another-key`
   - A Regular Expression (which flavor?) like `prefix-.*`
   - A Glob pattern like `prefix-*`
   - A search string (to be used in the [already existing key/name filtering](https://github.com/featbit/featbit/blob/065f9d040853fd66f16589509ef5793948acea17/modules/back-end/src/Infrastructure/FeatureFlags/FeatureFlagService.cs#L25-L34%5c))

3. **Remove [the valid JSON requirement](https://github.com/featbit/featbit/blob/065f9d040853fd66f16589509ef5793948acea17/modules/front-end/src/app/core/components/webhook-drawer/webhook-drawer.component.ts#L132-L138) for the Payload Template**
- Similar requirement on [the backend](https://github.com/featbit/featbit/blob/065f9d040853fd66f16589509ef5793948acea17/modules/back-end/src/Infrastructure/Webhooks/WebhookSender.cs#L40C13-L40C41).
- This should still be okay, as Handlebars.js should still allow you to make a malformed body if you so choose, though a warning could be handy to catch mistakes where valid JSON is expected.
- Then you could produce an empty body via Handlebars.js like this for a non-desired key:

```
{{#eq data.object.key "desired-key"}}
// Desired body goes here
{{/eq}}
```

- This would also require FeatBit to not send a request if it was empty, and this would probably need to be done via an additional checkbox so users can control this behavior.
- This means that something in the Featbit Backend ([inside here ](https://github.com/featbit/featbit/blob/065f9d040853fd66f16589509ef5793948acea17/modules/back-end/src/Api/Controllers/WebhookController.cs#L66-L71) somewhere? Or [here](https://github.com/featbit/featbit/blob/065f9d040853fd66f16589509ef5793948acea17/modules/back-end/src/Infrastructure/Webhooks/WebhookSender.cs#L31)?) would have to be changed too.

**Describe alternatives you've considered**
See the above discussion on different solution ideas.
I am of course open to other ideas, provided they do not require significantly altering how we organize or otherwise use FeatBit.

**Additional context**
If this cannot be put into the GitHub FeatBit repository in a reasonable time, I may be forced to implement one of these solutions in our internal fork of the repo so we can use it sooner to comply with the MS Teams deprecation deadline.

**Is this feature something you're interested in working on?**
Yes! I am available to work on this for the next couple of weeks.

**Comment by deleteLater** [comment]
Hi @drewsteinacher , thanks for your input!

Option 1 is more complete but also more complex to implement. For selecting the scopes, we actually already have a resource finder (PR #620)  for this scenario, it's a dialog and looks like this

![image](https://github.com/user-attachments/assets/6ebe1568-ecd8-4ff1-bea4-9ed6bba9017b)

Compare option 3 with 2, I prefer 3 because it's easier to implement and more general, though a little bit hacky. But I don't think we need to remove the validation; we can just allow an empty JSON `{}` and the user can decide whether to send the payload if it's an empty JSON as you said.

**Comment by drewsteinacher** [comment]
Thanks @deleteLater! It looks like `resource-finder` should greatly simplify Option 1. I will investigate more deeply soon.

Regarding the other options: Would it be acceptable to implement your proposal to allow an empty JSON object via a new checkbox, and then perhaps at a later time implement Option 1 with `resource-finder`? Or would you prefer to only have Option 1 implemented long-term?

**Comment by drewsteinacher** [comment]
I opted for the empty request checkbox route for now. I may be able to look at the `resource-finder` for Option 1 next week.
Let me know if there's anything I can do to help with this!

**Comment by drewsteinacher** [comment]
@deleteLater Thanks for the assist on this! The changes you added to the PR look good to me!

I did some looking into using `resource-finder`, but I think I will hold off on doing this work for the following reasons:
1. The `resource-finder` component probably needs to be updated to change [the text that describes what a resource is](https://github.com/drewsteinacher/featbit/blob/1143abaadf09eb971f345bdcf29eef903144fc8f/modules/front-end/src/app/core/components/resource-finder/resource-finder.component.html#L12-L12) to indicate which resources are being filtered to via the `resources` `@Input()`. It's unclear to me if this text is intended to be dynamic like this or not.
2. I was unable to get feature flags to be returned from the `ResourceService` on the backend. It appears that the functionality for [matching on feature flags does not yet exist](https://github.com/drewsteinacher/featbit/blob/1143abaadf09eb971f345bdcf29eef903144fc8f/modules/back-end/src/Infrastructure/Resources/ResourceServiceV2.cs#L29-L35) and it doesn't look all that easy to accomplish.
3. The new "Prevent Empty Payloads" checkbox implemented in the PR is sufficient for my needs.

If there's anything else I can do to help get this merged in, please let me know! Thanks!

**Comment by deleteLater** [comment]
You're welcome. Yeah the `resource-finder` currently does not support feature flags & segments, and the description text is fixed, not dynamic. It just haven't finished yet 😅. To accomplish that, both the API and UI have some work to do and we also tend to use a different RN strategy in `ResourceV2`. That's why I said it's complex.

I've merged your PR and will release a new version soon.

**Comment by deleteLater** [comment]
Since PR #681 has been merged, I'll close the issue and anyone is welcome to open again.
